import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';
import '@mantine/charts/styles.css';
import "./globals.css"
import type {Metadata} from "next";
import CustomAppShell from "@/app/_components/Navigation/CustomAppShell";
import {ColorSchemeScript, MantineProvider, mantineHtmlProps, createTheme} from '@mantine/core';
import { Notifications } from '@mantine/notifications';
import {LazyMotion, domAnimation} from "motion/react"
import {orbitron} from "@/app/fonts";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const theme = createTheme({

});

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {


    const defaultScheme = "light";


    return (
        <html lang="en" {...mantineHtmlProps} className={orbitron.className}>
        <head>
            <ColorSchemeScript defaultColorScheme={defaultScheme}/>
            <title>
                HackCU 2026
            </title>
        </head>
        <body>
            <MantineProvider defaultColorScheme={defaultScheme} theme={theme}>
                <Notifications/>
                <LazyMotion features={domAnimation}>
                    <CustomAppShell>
                        {children}
                    </CustomAppShell>
                </LazyMotion>
            </MantineProvider>
        </body>
        </html>
    );
}
